# Generated by Django 5.1.1 on 2024-11-11 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookchapter',
            name='chapter_title',
            field=models.CharField(blank=True, default='Untitled Chapter', max_length=255),
        ),
    ]
