# Generated by Django 5.1.1 on 2024-10-17 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, help_text='Short description of the book', null=True),
        ),
    ]
