# Generated by Django 5.1.1 on 2024-10-19 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_service', '0002_book_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookchapter',
            name='end_page_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookchapter',
            name='start_page_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
