# Generated by Django 5.1.1 on 2024-10-14 17:48

import django.db.models.deletion
import text_service.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('user_id', models.UUIDField(editable=False)),
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('file_path', models.CharField(help_text='Path should be in the format: /<UUID user>/<UUID book>', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cover_image', models.ImageField(blank=True, help_text='Upload a cover image for the book', max_length=500, null=True, upload_to=text_service.models.book_cover_upload_path)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookChapter',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('file_path', models.CharField(help_text='Full path format: /<UUID user>/<UUID book>/<file name>', max_length=500)),
                ('start_page_number', models.IntegerField()),
                ('end_page_number', models.IntegerField()),
                ('chapter_title', models.CharField(blank=True, max_length=255, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='text_service.book')),
            ],
        ),
        migrations.CreateModel(
            name='BookGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='text_service.book')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='text_service.genre')),
            ],
            options={
                'unique_together': {('book', 'genre')},
            },
        ),
    ]
