# Generated by Django 5.1.1 on 2024-10-11 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookChapter',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('file_path', models.CharField(max_length=500)),
                ('start_page_number', models.IntegerField()),
                ('end_page_number', models.IntegerField()),
                ('chapter_title', models.CharField(blank=True, max_length=255, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='text_service.book')),
            ],
        ),
    ]
